set(COMPONENT_NAME ospray)

set(COMPONENT_PATH ${CMAKE_INSTALL_PREFIX})

if (TRUE)
  if (BUILD_LATEST)
    set(HASH ${${COMPONENT_NAME}_HASH_LATEST})
  else()
    set(HASH ${${COMPONENT_NAME}_HASH_STABLE})
  endif()

  ExternalProject_Add(${COMPONENT_NAME}
    PREFIX ${COMPONENT_NAME}
    GIT_REPOSITORY https://github.com/RenderKit/ospray.git
    GIT_TAG ${HASH}
    STAMP_DIR ${COMPONENT_NAME}/stamp
    SOURCE_DIR ${COMPONENT_NAME}/src
    BINARY_DIR ${COMPONENT_NAME}/build
    SOURCE_SUBDIR scripts/superbuild
    INSTALL_COMMAND ""
    LIST_SEPARATOR | # Use the alternate list separator
    CMAKE_ARGS
      -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
      -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
      -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
      -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
      -DCMAKE_INSTALL_PREFIX:PATH=${COMPONENT_PATH}
      -DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR}
      -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}
      -DCMAKE_INSTALL_DOCDIR=${CMAKE_INSTALL_DOCDIR}
      -DCMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR}
      -DINSTALL_IN_SEPARATE_DIRECTORIES=OFF
      -DBUILD_TBB_FROM_SOURCE:BOOL=${OSPRAY_BUILD_TBB_FROM_SOURCE}
      -DBUILD_OPENVKL_FROM_SOURCE:BOOL=${OSPRAY_BUILD_OPENVKL_FROM_SOURCE}
    BUILD_COMMAND ${DEFAULT_BUILD_COMMAND}
    BUILD_ALWAYS ${ALWAYS_REBUILD}
  )
endif()

set(OSPRAY_PATH "${COMPONENT_PATH}")
list(APPEND CMAKE_PREFIX_PATH ${COMPONENT_PATH})
string(REPLACE ";" "|" CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}")
