name: anari-superbuild CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 5 * * *'
      branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2022]
        config: [Release, Debug]
        cuda: [ON, OFF]
        exclude:
          - os: macos-15
            cuda: ON
          - os: windows-2022 # need to get cuda working on windows first!
            cuda: ON

    name: OS ${{ matrix.os }} - config ${{ matrix.config }} - CUDA ${{ matrix.cuda }}

    steps:
    - uses: actions/checkout@v4

    - name: Add NVIDIA package repositories (Linux)
      if: >-
        matrix.os == 'ubuntu-24.04' &&
        matrix.cuda == 'ON'
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
        sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
        sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
        sudo apt update

    - name: Add NVIDIA package repositories (Windows)
      if: >-
        matrix.os == 'windows-2022' &&
        matrix.cuda == 'ON'
      run: |
        curl -L "https://developer.download.nvidia.com/compute/cuda/12.6.3/local_installers/cuda_12.6.3_561.17_windows.exe" -o ${{ github.workspace}}/cuda_12.6.3_561.17_windows.exe

    - name: Install CUDA (Linux)
      if: >-
        matrix.os == 'ubuntu-24.04' &&
        matrix.cuda == 'ON'
      run: sudo apt-get install -y cuda-toolkit-12-6

    - name: Install CUDA (Windows)
      if: >-
        matrix.os == 'windows-2022' &&
        matrix.cuda == 'ON'
      run: ${{ github.workspace}}/cuda_12.6.3_561.17_windows.exe -s

    
    - name: Setup CUDA (Linux)
      if: >-
        matrix.os == 'ubuntu-24.04' &&
        matrix.cuda == 'ON'
      run: |
        echo "/usr/local/cuda-12.6/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Setup CUDA (Windows)
      if: >-
        matrix.os == 'windows-2022' &&
        matrix.cuda == 'ON'
      run: |
        echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin" >> GITHUB_PATH

    - name: Install apt packages
      if: matrix.os == 'ubuntu-24.04'
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev libgtk-3-dev libglfw3-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev xorg-dev

    - name: Install homebrew packages
      if: matrix.os == 'macos-15'
      run: brew install boost glfw

    - name: Install vcpkg packages
      if: matrix.os == 'windows-2022'
      run: vcpkg install glfw3

    - name: Configure
      run: >
        cmake -LA -B ${{ github.workspace }}/build
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        -DDEPENDENCIES_BUILD_TYPE=${{ matrix.config }}
        -DBUILD_LATEST=${{ github.event_name == 'schedule' }}
        -DWITH_CUDA=${{ matrix.cuda }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.config }}
