name: anari-superbuild CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 5 * * *'
      branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
        config: [Release, Debug]

    name: OS ${{ matrix.os }} - config ${{ matrix.config }}

    steps:
    - uses: actions/checkout@v3

    - name: Install apt packages
      if: matrix.os == 'ubuntu-24.04'
      run: sudo apt install -y libboost-all-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev xorg-dev

    - name: Install homebrew packages
      if: matrix.os == 'macos-15'
      run: brew install boost libx11

    - name: Configure
      run: >
        cmake -LA -B ${{ github.workspace }}/build
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.config }}
